export const cardData = [
  {
    id: 1,
    title: "숨겨진 감정",
    question: "당신이 가장 숨기고 싶은 감정은?",
    category: "감정",
    img: "src/assets/picture1.png",
  },
  {
    id: 2,
    title: "진짜 나",
    question: "당신을 가장 당신답게 만드는 것은?",
    category: "자아",
    img: "src/assets/picture2.png",
  },
  {
    id: 3,
    title: "두려움",
    question: "지금 가장 두려운 것은?",
    category: "불안",
    img: "src/assets/picture3.png",
  },
  {
    id: 4,
    title: "기회",
    question: "놓치고 있는 기회는 무엇인가요?",
    category: "성장",
    img: "src/assets/picture4.png",
  },
  {
    id: 5,
    title: "흔들림",
    question: "최근 가장 흔들린 순간은?",
    category: "회고",
    img: "src/assets/picture5.png",
  },
  {
    id: 6,
    title: "위로",
    question: "지금 필요한 위로는?",
    category: "감정",
    img: "src/assets/picture6.png",
  },
  {
    id: 7,
    title: "갈망",
    question: "당신의 가장 큰 갈망은?",
    category: "욕구",
    img: "src/assets/picture7.png",
  },
  {
    id: 8,
    title: "내면",
    question: "내면의 진짜 목소리는?",
    category: "자아",
    img: "src/assets/picture8.png",
  },
  {
    id: 9,
    title: "회피",
    question: "가장 회피하고 있는 문제는?",
    category: "성찰",
    img: "src/assets/picture9.png",
  },
  {
    id: 10,
    title: "포기",
    question: "지금 포기하고 싶은 것은?",
    category: "선택",
    img: "src/assets/picture10.png",
  },
];
